from datetime import datetime


def get_default_schemes():
    return [
        {
            'name': 'PM-KISAN Samman Nidhi',
            'description': 'Rs. 6000 per year in three installments of Rs. 2000 through direct bank transfer.',
            'scheme_type': 'subsidy',
            'eligibility': 'All eligible farmers',
            'benefits': 'Direct bank transfer of income support.',
            'official_url': 'https://pmkisan.gov.in',
            'deadline': datetime(2026, 12, 31),
        },
        {
            'name': 'Pradhan Mantri Fasal Bima Yojana (PMFBY)',
            'description': 'Crop insurance against drought, flood, natural disasters, and other crop losses.',
            'scheme_type': 'insurance',
            'eligibility': 'Farmers growing notified crops',
            'benefits': 'Very low premium with crop loss protection.',
            'official_url': 'https://pmfby.gov.in',
            'deadline': datetime(2026, 12, 31),
        },
        {
            'name': 'PM-KUSUM',
            'description': 'Subsidy for solar pumps to reduce electricity cost and sell extra power.',
            'scheme_type': 'subsidy',
            'eligibility': 'Farmers interested in solar irrigation solutions',
            'benefits': 'Subsidy support for solar pump installation.',
            'official_url': 'https://pmkusum.mnre.gov.in',
            'deadline': datetime(2026, 12, 31),
        },
        {
            'name': 'Pradhan Mantri Krishi Sinchai Yojana (PMKSY)',
            'description': 'Improves irrigation with the goal of Har Khet Ko Pani.',
            'scheme_type': 'subsidy',
            'eligibility': 'Farmers needing irrigation support',
            'benefits': 'Irrigation development and water-use efficiency support.',
            'official_url': 'https://pmksy.gov.in',
            'deadline': datetime(2026, 12, 31),
        },
        {
            'name': 'Kisan Credit Card',
            'description': 'Easy loans for farmers for seeds, fertilizers, and other agricultural needs.',
            'scheme_type': 'subsidy',
            'eligibility': 'Eligible farmers needing short-term credit',
            'benefits': 'Low-interest credit support.',
            'official_url': 'https://www.financialservices.gov.in/beta/en/schemes/kisan-credit-card',
            'deadline': datetime(2026, 12, 31),
        },
        {
            'name': 'Paramparagat Krishi Vikas Yojana',
            'description': 'Promotes organic farming with financial support for sustainable practices.',
            'scheme_type': 'subsidy',
            'eligibility': 'Farmers adopting organic farming methods',
            'benefits': 'Support for organic inputs and certification.',
            'official_url': 'https://pgsindia-ncof.gov.in',
            'deadline': datetime(2026, 12, 31),
        },
        {
            'name': 'e-NAM',
            'description': 'Online mandi platform for better price discovery and smoother trade.',
            'scheme_type': 'subsidy',
            'eligibility': 'Farmers and traders using regulated markets',
            'benefits': 'Better market access and price discovery.',
            'official_url': 'https://enam.gov.in',
            'deadline': datetime(2026, 12, 31),
        },
        {
            'name': 'Tamil Nadu Crop Insurance Scheme',
            'description': 'Additional support over PMFBY for Tamil Nadu farmers.',
            'scheme_type': 'insurance',
            'eligibility': 'Tamil Nadu farmers',
            'benefits': 'Extra crop insurance coverage support.',
            'official_url': 'https://www.tn.gov.in/schemes',
            'deadline': datetime(2026, 12, 31),
        },
        {
            'name': 'Farm Mechanization Scheme Tamil Nadu',
            'description': 'Subsidy support for tractors, tools, and modern farm equipment.',
            'scheme_type': 'subsidy',
            'eligibility': 'Tamil Nadu farmers',
            'benefits': 'Subsidy on mechanization equipment.',
            'official_url': 'https://www.tn.gov.in/schemes',
            'deadline': datetime(2026, 12, 31),
        },
        {
            'name': 'Tamil Nadu Micro Irrigation Scheme',
            'description': 'Drip and sprinkler irrigation subsidy for efficient water use.',
            'scheme_type': 'subsidy',
            'eligibility': 'Tamil Nadu farmers',
            'benefits': 'Subsidy for micro irrigation systems.',
            'official_url': 'https://www.tn.gov.in/schemes',
            'deadline': datetime(2026, 12, 31),
        },
        {
            'name': 'Tamil Nadu Livestock Development Schemes',
            'description': 'Support for dairy, poultry, and livestock development activities.',
            'scheme_type': 'subsidy',
            'eligibility': 'Tamil Nadu farmers involved in livestock',
            'benefits': 'Financial support for livestock expansion.',
            'official_url': 'https://www.tn.gov.in/schemes',
            'deadline': datetime(2026, 12, 31),
        },
    ]
